services:
  postgres:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "phoenixexchange_dev"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - "./local_data:/var/lib/postgresql/data"
      - "./nasdaq-100.csv:/var/tmp/loader.csv"
